project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from baton.autodiscover import admin
from django.urls import path, include


def trigger_error(request):
    1 / 0


api_urlpatterns = [
    path("users/", include("xshop.users.api.urls", namespace="users_api")),
    path("products/", include("xshop.products.api.urls", namespace="products_api")),
    path("orders/", include("xshop.orders.api.urls", namespace="orders_api")),
    path("invoices/", include("xshop.invoices.api.urls", namespace="invoices_api")),
    path("shops/", include("xshop.shops.api.urls", namespace="shops_api")),
    path("cart/", include("xshop.cart.api.urls", namespace="cart_api")),
    path("", include("xshop.pages.api.urls", namespace="pages_api")),
]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("baton/", include("baton.urls")),
    path("users/", include("xshop.users.urls", namespace="users")),
    path("users/", include("django.contrib.auth.urls")),
    path("invoices/", include("xshop.invoices.urls", namespace="invoices")),
    path("core/", include("xshop.core.urls", namespace="core")),
    path("cart/", include("xshop.cart.urls", namespace="cart")),
    path("shop/", include("xshop.shops.urls", namespace="shop")),
    path("product/", include("xshop.products.urls", namespace="product")),
    path("orders/", include("xshop.orders.urls", namespace="order")),
    path("payments/", include("xshop.payments.urls", namespace="payments")),
    path("api/", include(api_urlpatterns)),  # API urls from above
    path("", include("xshop.pages.urls", namespace="pages")),
    # for testing error alerts
    # path("sentry-debug/", trigger_error),
]

# media & static urls
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

xshop/cart/api/urls.py
from django.urls import path

from . import views

app_name = "cart_api"

urlpatterns = [
    path("", views.CartApi.as_view(), name="cart_operations"),
]

xshop/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart_ops"),
]

xshop/orders/urls.py
from django.urls import path

from . import views


app_name = "orders"

urlpatterns = [
    path("checkout/", views.CheckOutView.as_view(), name="checkout"),
]

xshop/pages/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from .views import Home

app_name = "pages"

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="footer_pages/about.html"),
        name="about",
    ),
    path(
        "thankyou/",
        TemplateView.as_view(template_name="pages/thankyou.html"),
        name="thankyou",
    ),
    path(
        "terms/",
        TemplateView.as_view(template_name="footer_pages/terms.html"),
        name="terms",
    ),
    path(
        "privacy_policy/",
        TemplateView.as_view(template_name="footer_pages/privacy_policy.html"),
        name="privacy_policy",
    ),
    path(
        "services/",
        TemplateView.as_view(template_name="footer_pages/services.html"),
        name="services",
    ),
]

xshop/shops/urls.py
from django.urls import path

from . import views

app_name = "shop"

urlpatterns = [
    path("", views.ShopsSearchView.as_view(), name="shop_search"),
    path("<slug:shop_subdomain>/", views.ShopDetailView.as_view(), name="shop_details"),
]

xshop/users/urls.py
from django.urls import path

from xshop.users import views

app_name = "users"

urlpatterns = [
    path("redirection/", views.redirection, name="redirection"),
    path("login/", views.Login.as_view(), name="login"),
    path("register/", views.register, name="register"),
]

xshop/cart/forms.py
from django import forms

from xshop.products.models import Product
from xshop.products.api.serializers import ProductSerializer


class CartPostProductForm(forms.Form):
    quantity = forms.IntegerField(
        widget=forms.TextInput(
            attrs={"class": "form-control-lg", "id": "quantity_input"}
        )
    )
    actions = forms.CharField(required=False, initial="add", widget=forms.HiddenInput)
    product_id = forms.IntegerField(required=True, widget=forms.HiddenInput)

    def clean(self):
        attrs = super().clean()
        quantity = attrs.get("quantity")
        action = attrs.get("actions")
        product_id = attrs.get("product_id")

        if action == "clear":
            return attrs

        try:
            product = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            raise forms.ValidationError({"product_id": "Not found"})
        if action == "update" and quantity is None:
            raise forms.ValidationError({"quantity": "invalid, must provide quantity"})
        if action == "update" and product.stock < quantity:
            raise forms.ValidationError(
                {"quantity": f"Invalid. available stock {product.stock}"}
            )

        attrs["product"] = ProductSerializer(product).data
        return attrs

xshop/cart/api/views.py
from rest_framework.permissions import IsAuthenticated
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from drf_spectacular.utils import extend_schema


from .serializers import CartSerializer
from ..cart import Cart


class CartApi(APIView):
    serializer_class = CartSerializer
    permission_classes = [IsAuthenticated]

    @extend_schema(
        description="Add, Update or remove product to cart or Delete the cart itself",
        request=CartSerializer,
        responses={
            200: CartSerializer,
            400: [{"product_id": "Not found"}, {"quantity": "Invalid"}],
        },
    )
    def post(self, request):
        cart = Cart(request)
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        action = serializer.validated_data.get("actions")

        if action == "add":
            product = serializer.validated_data.get("product")
            cart.add(product=product)
            return Response(cart)

        elif action == "patch":
            product = serializer.validated_data.get("product")

            cart.update(
                product=product,
                quantity=serializer.validated_data.get("quantity"),
            )
            return Response(cart)

        elif action == "remove":
            product = serializer.validated_data.get("product")
            cart.remove(product)
            return Response(cart, status=status.HTTP_200_OK)

        elif action == "clear":
            cart.clear()
            return Response(status.HTTP_200_OK)

    @extend_schema(
        description="get cart's product",
        responses={200: CartSerializer},
    )
    def get(self, request):
        cart = Cart(request)

        return Response(cart)

xshop/cart/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django import forms

from xshop.cart.cart import Cart
from xshop.cart.forms import CartPostProductForm
from xshop.products.models import Product
from xshop.cart.api.serializers import ProdcutCartSerializer


class CartView(LoginRequiredMixin, ListView):
    def post(self, request):
        cart = Cart(request)
        form = CartPostProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            action = cd["actions"]
            product = cd["product"]

            if action == "update":
                quantity = int(cd["quantity"])
                cart.update(
                    product=product,
                    quantity=quantity,
                )

                return redirect("cart:cart_ops")
        if request.POST.get("action") == "update":
            product_id = int(request.POST.get("productid"))
            try:
                product = Product.objects.get(id=product_id)
                product_json = ProdcutCartSerializer(product).data
                quantity = int(request.POST.get("quantity"))
                if product.stock < quantity:
                    raise forms.ValidationError(
                        {"quantity": f"Invalid. available stock {product.stock}"}
                    )
                cart.update(
                    product=product_json,
                    quantity=quantity,
                )

                return redirect("cart:cart_ops")

            except Product.DoesNotExist:
                form.errors["product_id"] = "Not found"

        if request.POST.get("actions") == "add":
            product_id = int(request.POST.get("product_id"))
            try:
                product = Product.objects.get(id=product_id)
                product_json = ProdcutCartSerializer(product).data
                cart.add(product=product_json)

                return redirect("cart:cart_ops")
            except Product.DoesNotExist:
                form.errors["product_id"] = "Not found"

        if request.POST.get("action") == "remove":
            product_id = int(request.POST.get("productid"))
            product = Product.objects.get(id=product_id)
            product_json = ProdcutCartSerializer(product).data
            cart.remove(product_json)
            return redirect("cart:cart_ops")

        if request.POST.get("action") == "clear":
            cart.clear()

            return redirect("cart:cart_ops")

        full_price = 0
        for item in cart:
            full_price += item["total_price"]
            item["update_quantity_form"] = CartPostProductForm(
                initial={
                    "quantity": item["quantity"],
                    "actions": "update",
                    "product_id": item["product"]["id"],
                }
            )
        context = {
            "cart": cart,
            "full_price": full_price,
            "user": request.user,
            "errors": form.errors,
        }
        return render(request, "pages/cart.html", context)

    def get(self, request):
        cart = Cart(request)
        full_price = 0
        for item in cart:
            full_price += item["total_price"]
            item["update_quantity_form"] = CartPostProductForm(
                initial={
                    "quantity": item["quantity"],
                    "actions": "update",
                    "product_id": item["product"]["id"],
                }
            )
        context = {
            "cart": cart,
            "full_price": full_price,
            "user": request.user,
            "quantity_range": range(1, 10),
            "ui": range(12),
        }
        return render(request, "pages/cart.html", context)

templates/pages/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<title>X-SHOP</title>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">
	<link rel="stylesheet" href="{% static 'home_assets/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'home_assets/fonts/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'home_assets/fonts/ionicons.min.css' %}">
	<link rel="stylesheet" href="{% static 'home_assets/css/Footer-Basic.css' %}">
	<link rel="stylesheet" href="{% static 'home_assets/css/Footer-Dark.css' %}">
	<link rel="stylesheet" href="{% static 'home_assets/css/Header-Blue.css' %}">
	<link rel="stylesheet" href="{% static 'home_assets/css/Projects-Clean.css' %}">
	<link rel="stylesheet" href="{% static 'home_assets/css/styles.css' %}">
</head>

<body>
	<header class="header-blue" style="height: 1278.2px;">
		<nav class="navbar navbar-dark navbar-expand-md navigation-clean-search" style="height: 75;">
			<div class="container-fluid">
				<a href="{% url 'pages:home' %}">
					<img src="{% static 'home_assets/img/x.jpg' %}" style="width: 110px;height: 58px;padding-left: 5px;">
				</a>
				<button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
					<span class="sr-only">
						Toggle navigation
					</span>
					<span class="navbar-toggler-icon">
					</span>
				</button>
				<div class="collapse navbar-collapse" id="navcol-1">
					<ul class="navbar-nav"></ul>
					<form class="form-inline ml-auto" action="{% url 'shop:shop_search' %}" method="get">
						<div class="form-group mb-0" style="width: 236.9px;">
							<label for="search-field">
								<i class="fa fa-search" style="filter: brightness(106%);">
								</i>
							</label>
							<input class="form-control search-field" type="search" id="search-field" name="search_by" placeholder="Shops Search"
								style="font-size: 19.49px;color: var(--white);filter: blur(0px) brightness(123%) contrast(109%) grayscale(24%) hue-rotate(53deg) saturate(200%);">
						</div>
					</form>
					{% if user.is_authenticated %}
                    <a href="{% url 'cart:cart_ops' %}">
						<i class="fa fa-shopping-cart border-primary shadow-lg float-right d-xl-flex justify-content-center align-items-center justify-content-xl-end align-items-xl-end"
							data-toggle="tooltip" data-bss-tooltip="" data-placement="left" title="cart"
							style="color: #dbe8f5;font-size: 20px;margin: 10px;padding: 0px;width: 53.2px;height: 20px;text-align: right;border-style: none;border-color: var(--red);border-radius: -6px;margin-top: 22px;margin-bottom: 10px;">
						</i>
                    </a>
						<label class="text-left float-left d-xl-flex justify-content-end"
							style="height: 30px;margin: 10px;width: 110.9px;padding: 1px;color: rgb(214,233,251);font-size: 16px;margin-top: 15px;margin-left: 0px;margin-right: 10px;">
							{{ user.mobile }}
						</label>
							<a class="btn btn-light action-button" role="button" href="{% url 'logout' %}" style="filter: brightness(100%);">
								Log Out
							</a>
          {% else %}
            <span class="navbar-text" style="filter: brightness(165%);">
              <a class="login" href="{% url 'users:login' %}" style="filter: brightness(71%);">
                Log In
              </a>
            </span>
            <a class="btn btn-light action-button" role="button" href="{% url 'users:register' %}" style="filter: brightness(100%);">
              Sign Up
            </a>
          {% endif %}
                </div>
            </div>
        </nav>
        <section class="projects-clean">
            <div class="container">
                <div class="intro">
                    <h2 class="text-center">SHOPS</h2>
                    <form class="form-inline mr-auto" target="_self">
                        <div class="form-group mb-0"><label for="search-field"></label></div>
                    </form>
                </div>
            </div>
            <div class="container">
                <div class="intro"></div>
                <div class="row projects">
                    {% for shop in shops %}
                    <div class="col-sm-6 col-lg-4 item">
                        <a class="img-fluid" href="{% url 'shop:shop_details' shop.subdomain %}">
                            <img class="img-fluid" src="{{ shop.picture.url }}">
                        </a>
                        <h3 class="name">{{ shop.name }}</h3>
                        <p class="description">{{ shop.description }}</p>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        <footer class="footer-basic" style="background: #022534;">
            <div class="social">
                <a href="https://github.com/egypt-shops/xshop-docs" style="filter: brightness(200%);opacity: 1;"><i class="icon ion-social-instagram" style="filter: brightness(120%);"></i></a>
                <a href="https://github.com/egypt-shops/xshop-docs" style="opacity: 1;filter: brightness(200%);"><i class="icon ion-social-github" style="filter: brightness(120%);"></i></a>
                <a href="https://github.com/egypt-shops/xshop-docs" style="filter: brightness(200%);opacity: 1;"><i class="icon ion-social-twitter" style="filter: brightness(120%);"></i></a>
                <a href="https://github.com/egypt-shops/xshop-docs" style="opacity: 1;filter: brightness(200%);"><i class="icon ion-social-facebook" style="filter: brightness(120%);"></i></a></div>
            <ul class="list-inline">
                <!-- <li class="list-inline-item" style="filter: brightness(132%);"><a href="#" style="filter: brightness(200%);">Home</a></li> -->
                <li class="list-inline-item" style="filter: brightness(132%);"><a href="{% url 'pages:services' %}" style="filter: brightness(200%);">Services</a></li>
                <li class="list-inline-item" style="filter: brightness(132%);"><a href="{% url 'pages:about' %}" style="filter: brightness(200%);">About</a></li>
                <li class="list-inline-item" style="filter: brightness(132%);"><a href="{% url 'pages:terms' %}" style="filter: brightness(200%);">Terms</a></li>
                <li class="list-inline-item" style="filter: brightness(132%);"><a href="{% url 'pages:privacy_policy' %}" style="opacity: 1;filter: brightness(200%);">Privacy Policy</a></li>
            </ul>
            <p class="copyright">X-Shop © 2021</p>
        </footer>
    </header>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>

templates/pages/product_detail.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <title>product_details</title>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/product_details.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'product_assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'product_assets/fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'product_assets/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'product_assets/css/Footer-Basic.css' %}">
    <link rel="stylesheet" href="{% static 'product_assets/css/Header-Blue.css' %}">
    <link rel="stylesheet" href="{% static 'product_assets/css/Header-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'product_assets/css/styles.css'">
    <link rel="stylesheet" href="{% static 'product_assets/css/Team-Boxed.css' %}">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" -->
    <!-- integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous"> -->
</head>



<header>
    <a href="{% url 'pages:home' %}">
        <img style="padding-left: 20px;" class="logo" src="{% static 'css/logo.jpg' %}" alt="">
    </a>
    <a style="padding-left: 600px;" href="{% url 'cart:cart_ops' %}" aria-label="Go to Cart" target="_blank">
        <span class="glyphicon glyphicon-shopping-cart">
        </span>
    </a>

</header>

<h1 class="pname">{{ product.name }}</h1>
    <div>
        <img class="pimage" src="{{ product.picture.url }}" alt="">
        <span class="price">{{ price }} <span style="color:#08304d"> EGP</span> </span>
        <button class="add add-button" style="font-size:24px" name="add to cart" data-index='{{ product.id }}'> Add to Cart <i
                class="fa fa-shopping-cart"></i></button>
    </div>

    <div style="padding-left: 100px; padding-top: 25px; padding-bottom: 25px;">
        <h2>Rating</h2>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star checked"></span>
        <span class="fa fa-star"></span>
        <span class="fa fa-star"></span>
    </div>
    <h2 class="description">DESCRIPTION</h2>
    <p>{{ product.description }}</p>
        <footer class="footer-basic" style="background: #022534;">
            <div class="social">
                <a href="https://github.com/egypt-shops/xshop-docs" style="filter: brightness(200%);opacity: 1;"><i class="icon ion-social-instagram" style="filter: brightness(120%);"></i></a>
                <a href="https://github.com/egypt-shops/xshop-docs" style="opacity: 1;filter: brightness(200%);"><i class="icon ion-social-github" style="filter: brightness(120%);"></i></a>
                <a href="https://github.com/egypt-shops/xshop-docs" style="filter: brightness(200%);opacity: 1;"><i class="icon ion-social-twitter" style="filter: brightness(120%);"></i></a>
                <a href="https://github.com/egypt-shops/xshop-docs" style="opacity: 1;filter: brightness(200%);"><i class="icon ion-social-facebook" style="filter: brightness(120%);"></i></a></div>
            <ul class="list-inline">
                <!-- <li class="list-inline-item" style="filter: brightness(132%);"><a href="#" style="filter: brightness(200%);">Home</a></li> -->
                <li class="list-inline-item" style="filter: brightness(132%);"><a href="{% url 'pages:services' %}" style="filter: brightness(200%);">Services</a></li>
                <li class="list-inline-item" style="filter: brightness(132%);"><a href="{% url 'pages:about' %}" style="filter: brightness(200%);">About</a></li>
                <li class="list-inline-item" style="filter: brightness(132%);"><a href="{% url 'pages:terms' %}" style="filter: brightness(200%);">Terms</a></li>
                <li class="list-inline-item" style="filter: brightness(132%);"><a href="{% url 'pages:privacy_policy' %}" style="opacity: 1;filter: brightness(200%);">Privacy Policy</a></li>
            </ul>
            <p class="copyright">X-Shop © 2021</p>
        </footer>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

<script>
    $(document).on('click', '.add-button', function (e) {
        e.preventDefault();
        var remove_id = $(this).data('index')
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_ops" %}',
            data: {
                product_id: $(this).data('index'),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                actions: 'add'
            },
            success: function (json) {
                location.reload();
            },
            error: function (xhr, errmsg, err) { }
        });
    });
</script>
</body>

</html>

templates/pages/shops_search_results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<title>X-SHOP</title>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">
	<link rel="stylesheet" href="{% static 'home_assets/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'home_assets/fonts/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'home_assets/fonts/ionicons.min.css' %}">
	<link rel="stylesheet" href="{% static 'home_assets/css/Footer-Basic.css' %}">
	<link rel="stylesheet" href="{% static 'home_assets/css/Footer-Dark.css' %}">
	<link rel="stylesheet" href="{% static 'home_assets/css/Header-Blue.css' %}">
	<link rel="stylesheet" href="{% static 'home_assets/css/Projects-Clean.css' %}">
	<link rel="stylesheet" href="{% static 'home_assets/css/styles.css' %}">
</head>

<body>
	<header class="header-blue" style="height: 1278.2px;">
		<nav class="navbar navbar-dark navbar-expand-md navigation-clean-search" style="height: 75;">
			<div class="container-fluid">
				<a href="{% url 'pages:home' %}">
					<img src="{% static 'home_assets/img/x.jpg' %}" style="width: 110px;height: 58px;padding-left: 5px;">
				</a>
				<button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
					<span class="sr-only">
						Toggle navigation
					</span>
					<span class="navbar-toggler-icon">
					</span>
				</button>
				<div class="collapse navbar-collapse" id="navcol-1">
					<ul class="navbar-nav"></ul>
						<form class="form-inline ml-auto" action="{% url 'shop:shop_search' %}" method="get">
							<div class="form-group mb-0" style="width: 236.9px;">
								<label for="search-field">
									<i class="fa fa-search" style="filter: brightness(106%);">
									</i>
								</label>
								<input class="form-control search-field" name="search_by" type="search" id="search-field" placeholder="Shops Search"
									style="font-size: 19.49px;color: var(--white);filter: blur(0px) brightness(123%) contrast(109%) grayscale(24%) hue-rotate(53deg) saturate(200%);">
							</div>
						</form>
					{% if user.is_authenticated %}
					<a href="{% url 'cart:cart_ops' %}">
					<i class="fa fa-shopping-cart border-primary shadow-lg float-right d-xl-flex justify-content-center align-items-center justify-content-xl-end align-items-xl-end"
						data-toggle="tooltip" data-bss-tooltip="" data-placement="left" title="cart"
						style="color: #dbe8f5;font-size: 20px;margin: 10px;padding: 0px;width: 53.2px;height: 20px;text-align: right;border-style: none;border-color: var(--red);border-radius: -6px;margin-top: 22px;margin-bottom: 10px;">
					</i>
					</a>
					<label class="text-left float-left d-xl-flex justify-content-end"
						style="height: 30px;margin: 10px;width: 110.9px;padding: 1px;color: rgb(214,233,251);font-size: 16px;margin-top: 15px;margin-left: 0px;margin-right: 10px;">
						{{ user.mobile }}
					</label>

					<a class="btn btn-light action-button" role="button" href="{% url 'logout' %}"
						style="filter: brightness(100%);">
						Log Out
					</a>
					{% else %}
					<span class="navbar-text" style="filter: brightness(165%);">
						<a class="login" href="{% url 'users:login' %}" style="filter: brightness(71%);">
							Log In
						</a>
					</span>
					<a class="btn btn-light action-button" role="button" href="{% url 'users:register' %}"
						style="filter: brightness(100%);">
						Sign Up
					</a>
					{% endif %}
				</div>
			</div>
		</nav>
		<section class="projects-clean">
			<div class="container">
				<div class="intro">
					<h2 class="text-center">SHOPS</h2>
					<form class="form-inline mr-auto" target="_self">
						<div class="form-group mb-0"><label for="search-field"></label></div>
					</form>
				</div>
			</div>
			<div class="container">
				<div class="intro"></div>
				<div class="row projects">
						{% for shop in shops %}
							<div class="col-sm-6 col-lg-4 item">
								<a class="img-fluid" href="{% url 'shop:shop_details' shop.subdomain %}">
									<img class="img-fluid" src="{{ shop.picture.url }}">
								</a>
								<h3 class="name">{{ shop.name }}</h3>
								<p class="description">{{ shop.description }}</p>
							</div>
						{% endfor %}
				</div>
			</div>
		</section>
		<footer class="footer-basic" style="background: #022534;">
			<div class="social">
				<a href="https://github.com/egypt-shops/xshop-docs" style="filter: brightness(200%);opacity: 1;"><i
						class="icon ion-social-instagram" style="filter: brightness(120%);"></i></a>
				<a href="https://github.com/egypt-shops/xshop-docs" style="opacity: 1;filter: brightness(200%);"><i
						class="icon ion-social-github" style="filter: brightness(120%);"></i></a>
				<a href="https://github.com/egypt-shops/xshop-docs" style="filter: brightness(200%);opacity: 1;"><i
						class="icon ion-social-twitter" style="filter: brightness(120%);"></i></a>
				<a href="https://github.com/egypt-shops/xshop-docs" style="opacity: 1;filter: brightness(200%);"><i
						class="icon ion-social-facebook" style="filter: brightness(120%);"></i></a>
			</div>
			<ul class="list-inline">
				<!-- <li class="list-inline-item" style="filter: brightness(132%);"><a href="#" style="filter: brightness(200%);">Home</a></li> -->
                <li class="list-inline-item" style="filter: brightness(132%);"><a href="{% url 'pages:services' %}" style="filter: brightness(200%);">Services</a></li>
                <li class="list-inline-item" style="filter: brightness(132%);"><a href="{% url 'pages:about' %}" style="filter: brightness(200%);">About</a></li>
                <li class="list-inline-item" style="filter: brightness(132%);"><a href="{% url 'pages:terms' %}" style="filter: brightness(200%);">Terms</a></li>
                <li class="list-inline-item" style="filter: brightness(132%);"><a href="{% url 'pages:privacy_policy' %}" style="opacity: 1;filter: brightness(200%);">Privacy Policy</a></li>
			</ul>
			<p class="copyright">X-Shop © 2021</p>
		</footer>
	</header>
	<script src="assets/js/jquery.min.js"></script>
	<script src="assets/bootstrap/js/bootstrap.min.js"></script>
    </script>
</body>

</html>