project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from baton.autodiscover import admin
from django.urls import path, include


def trigger_error(request):
    1 / 0


api_urlpatterns = [
    path("users/", include("xshop.users.api.urls", namespace="users_api")),
    path("products/", include("xshop.products.api.urls", namespace="products_api")),
    path("orders/", include("xshop.orders.api.urls", namespace="orders_api")),
    path("invoices/", include("xshop.invoices.api.urls", namespace="invoices_api")),
    path("shops/", include("xshop.shops.api.urls", namespace="shops_api")),
    path("cart/", include("xshop.cart.api.urls", namespace="cart_api")),
    path("", include("xshop.pages.api.urls", namespace="pages_api")),
]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("baton/", include("baton.urls")),
    path("users/", include("xshop.users.urls", namespace="users")),
    path("users/", include("django.contrib.auth.urls")),
    path("invoices/", include("xshop.invoices.urls", namespace="invoices")),
    path("core/", include("xshop.core.urls", namespace="core")),
    path("cart/", include("xshop.cart.urls", namespace="cart")),
    path("shop/", include("xshop.shops.urls", namespace="shop")),
    path("product/", include("xshop.products.urls", namespace="product")),
    path("orders/", include("xshop.orders.urls", namespace="order")),
    path("payments/", include("xshop.payments.urls", namespace="payments")),
    path("api/", include(api_urlpatterns)),  # API urls from above
    path("", include("xshop.pages.urls", namespace="pages")),
    # for testing error alerts
    # path("sentry-debug/", trigger_error),
]

# media & static urls
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

xshop/cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart_ops"),
]

xshop/pages/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from .views import Home

app_name = "pages"

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="footer_pages/about.html"),
        name="about",
    ),
    path(
        "thankyou/",
        TemplateView.as_view(template_name="pages/thankyou.html"),
        name="thankyou",
    ),
    path(
        "terms/",
        TemplateView.as_view(template_name="footer_pages/terms.html"),
        name="terms",
    ),
    path(
        "privacy_policy/",
        TemplateView.as_view(template_name="footer_pages/privacy_policy.html"),
        name="privacy_policy",
    ),
    path(
        "services/",
        TemplateView.as_view(template_name="footer_pages/services.html"),
        name="services",
    ),
]

xshop/payments/urls.py
from django.urls import path
from xshop.payments import views

app_name = "payments"

urlpatterns = [
    path("result", views.result, name="result"),
]

xshop/payments/models.py
from django.core.exceptions import ValidationError
from django.db import models
from model_utils.models import TimeStampedModel

from xshop.cart.cart import Cart

# from xshop.payments import paymob


class PaymentAttempt(TimeStampedModel):
    # The mutual reference between us and the payment gateway (merchant_order_id in paymob)
    mutual_reference = models.CharField(
        max_length=36, blank=True, null=True, editable=False
    )
    gateway_transaction_id = models.CharField(
        max_length=36, blank=True, null=True, editable=False
    )
    status = models.CharField(max_length=12, blank=True, null=True, editable=False)
    order = models.ForeignKey("orders.Order", on_delete=models.PROTECT, editable=False)

    def clean(self):
        if self.order.paid:
            raise ValidationError("Payment can not be issued for a paid order")

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    def after(self, request):
        # NOTE Keep it dummy no need for too much validations, it's a GP anyway :3
        # make sure of transaction status from paymob
        # transaction_id = request_data.get("id")
        # transaction = paymob.retrieve_transaction(transaction_id)
        # # make sure same transaction
        # assert transaction.get("merchant_order_id") == self.mutual_reference

        request_data = request.GET

        # update payment attempt
        pending = request_data.get("pending")
        success = request_data.get("success")

        if pending == "false":
            if success == "true":
                self.status = "Successful"
            elif success == "false":
                self.status = "Failed"
        self.gateway_transaction_id = request_data.get("id")

        # commit db
        self.save()

        # mark order paid if successful attempt
        if self.status == "Successful":
            self.order.paid = True
            self.order.save()

        # clear cart after success
        cart = Cart(request)
        cart.clear()

xshop/payments/views.py
from django.shortcuts import get_object_or_404, render

from xshop.cart.cart import Cart
from xshop.payments.models import PaymentAttempt


def result(request):
    """Post Payment (Redirect Response from PayMob)"""
    data = request.GET

    # ========== Cash On Delivery
    if data.get("paying_method") == "CASH_ON_DELIVERY":

        # clear cart after payment
        cart = Cart(request)
        cart.clear()

        return render(
            request,
            "payments/result.dt.html",
            {
                "order_id": data.get("order_id"),
                "paying_method": data.get("paying_method"),
            },
        )

    # ========== Credit Card
    mutual_reference = data.get("merchant_order_id")
    payment_attempt = get_object_or_404(
        PaymentAttempt, mutual_reference=mutual_reference
    )
    payment_attempt.after(request)

    return render(
        request,
        "payments/result.dt.html",
        {
            "status": payment_attempt.status,
            "mutual_reference": mutual_reference,
            "order_id": payment_attempt.order.id,
            "paying_method": "CREDIT_CARD",
        },
    )

xshop/payments/templates/payments/result.dt.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'payments_statics/Thank.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Thank You</title>
</head>

<body>

    <header>

        <div class="cont2">

            <label for="search1" class="fa fa-search icon"></label>
            <input type="search" id="search1" class="search" placeholder="Products Search..">


            <label class="welcome"> <a class="fa fa-shopping-cart icon" href="{% url 'cart:cart_ops' %}"></a> welcome, name</label>

        </div>
        <a href="{% url 'pages:home' %}">
        <img class="logo" src="{% static 'payments_statics/logo.jpg' %}" alt="">
        </a>
    </header>

    <h1>Thank You!</h1>

    <span id="mark" class="fa fa-check-circle"></span>

    <!-- <h2>your order was completed successfully </h2> -->
    {% if paying_method == "CASH_ON_DELIVERY" %}
    <h2>Your order placed successfully!</h2>
    <h2>ID # {{ order_id }}</h2>
    <!-- <h2></h2> -->
    {% else %}
    {% if status == 'Successful' %}
    <h2>Your order placed successfully!</h2>
    {% else %}
    <h2>We failed to process your payment! Please try again.</h2>
    {% endif %}
    <h2>Reference: {{ mutual_reference }}</h2>
    {% endif %}



    <hr class="or">

    <h2>return to  <a class="home" href="{% url 'pages:home' %}"> home page </a> <br>
    </h2>


    <footer class="fooo">

        <div class="faa">
            <a href="https://github.com/egypt-shops/xshop-docs" class="fa fa-instagram"></a>
            <a href="https://github.com/egypt-shops/xshop-docs" class="fa fa-github"></a>
            <a href="https://github.com/egypt-shops/xshop-docs" class="fa fa-twitter"></a>
            <a href="https://github.com/egypt-shops/xshop-docs" class="fa fa-facebook"></a>
        </div>

        <div class="links">
            <a class="link1" href="{% url 'pages:services' %}">Services</a>
            <a class="link1" href="{% url 'pages:about' %}">About</a>
            <a class="link1" href="{% url 'pages:terms' %}">Terms</a>
            <a class="link1" href="{% url 'pages:privacy_policy' %}">Privacy Policy</a>
        </div>

        <p class="e-name">© 2021 Egypt Shops </p>

    </footer>

</body>

</html>

xshop/payments/templates/payments/result.dtold.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Payment Result</title>
</head>

<body>
  <h1>Thank you</h1>
  {% if paying_method == "CASH_ON_DELIVERY" %}
  <p>Your order placed successfully!</p>
  <p>ID # {{ order_id }}</p>
  {% else %}

  {% if status == 'Successful' %}
  <p>Your order placed successfully!</p>
  {% else %}
  <p>We failed to process your payment! Please try again.</p>
  {% endif %}
  <p>Reference: {{ mutual_reference }}</p>

  {% endif %}
</body>

</html>